HAWKES_METHOD_STR = 'hawkes'
MOVING_AVERAGE_METHOD_STR = 'movingaverage'
NAIVE_METHOD_STR = 'naive'
ORACLE_METHOD_STR = 'oracle'

DATA_DIRECTORY = 'data'
SAMPLED_COE_DF_SUBDIRECTORY = 'sampled_coe_dfs'
CONF_SAMPLING_FILE_PATH = 'data/conf_sampling_df.yml'

COE_TRAINING_DURATION_MINUTES = 30
