HAWKES_METHOD_STR = 'hawkes'
POISSON_METHOD_STR = 'poisson'
MOVING_AVERAGE_METHOD_STR = 'movingaverage'
NAIVE_METHOD_STR = 'naive'
ORACLE_METHOD_STR = 'oracle'

DATA_DIRECTORY = 'data_BTC_USD copy'
SAMPLED_COE_DF_SUBDIRECTORY = 'sampled_coe_dfs'
CONF_SAMPLING_FILE_PATH = f'{DATA_DIRECTORY}/conf_sampling_df.yml'

COE_TRAINING_DURATION_MINUTES = 30
